The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one

Denoted by Fn

Fn = 0 1 1 2 3 5 8 13 21



#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {int n,a=0,b=1,c;printf("%d",a);printf(" %d",b);
scanf("%d",&n);
for(int i=0;i<n-2;i++)
{c=a+b;
    printf(" %d",c);
    a=b;
    b=c;}
return 0;
}
